ar3:
  joint_offsets:
    JointRightShoulderPan: 0.0
    JointRightShoulderTilt: 0.0
    JointRightUpperArmRoll: 0.0
    JointRightElbowFlex: 0.0
    JointRightForearmRoll: 0.0
    JointRightWristFlex: 0.0
    JointRightWristRoll: 0.0
    JointRightGripper: 0.0
    JointLeftShoulderPan: 0.0
    JointLeftShoulderTilt: 0.0
    JointLeftUpperArmRoll: 0.0
    JointLeftElbowFlex: 0.0
    JointLeftForearmRoll: 0.0
    JointLeftWristFlex: 0.0
    JointLeftWristRoll: 0.0
    JointLeftGripper: 0.0
  joint_read_ratio:
    JointRightShoulderPan: 1.0
    JointRightShoulderTilt: 1.0
    JointRightUpperArmRoll: 1.0
    JointRightElbowFlex: 1.0
    JointRightForearmRoll: 1.0
    JointRightWristFlex: 1.0
    JointRightWristRoll: 1.0
    JointRightGripper: 1.0
    JointLeftShoulderPan: 1.0
    JointLeftShoulderTilt: 1.0
    JointLeftUpperArmRoll: 1.0
    JointLeftElbowFlex: 1.0
    JointLeftForearmRoll: 1.0
    JointLeftWristFlex: 1.0
    JointLeftWristRoll: 1.0
    JointLeftGripper: 1.0
